#! /usr/bin/env perl
# Copyright 2011-2026 Free Software Foundation, Inc.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Originally written by Patrice Dumas.

use strict;

use warnings;

use File::Find;
use File::Basename;
use File::Spec;

my ($program_name, $mydir, $suffix) = fileparse($0);
my $updir = File::Spec->updir();
my $parent = join('/', ($mydir, $updir, 'perl'));
chdir($parent) || die "chdir $parent: $!";
-d "t" || (die "goodbye, no t directory in " . `pwd`);

my @tap_files;
find(\&wanted_tap_files, ('t'));
sub wanted_tap_files {
  if (/\.t$/ and $File::Find::dir =~ /t(\/z_misc)?$/) {
    push @tap_files, $File::Find::name;
  }
}

open(INCLUDE, '>Makefile.tres') or die "Open Makefile.tres failed: $!";
print INCLUDE <<EOH;
# Makefile.tres generated by maintain/regenerate_tap_tests_lists.pl
#
EOH

print INCLUDE 'test_tap_files_generated_list =';
foreach my $file (sort(@tap_files)) {
  print INCLUDE " \\\n  $file";
}
print INCLUDE "\n\n";
